# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a6f4c49d4b33b2f650d6e706f988eae3df70df2e62e35501619894b314ee3ea75f901707bc9e7b13582d7e801c286fb6fd3c458bd6d41e0fd3e70e17050bd6f

test:
  secret_key_base: 028f2248d7aad74af004eef54ac0f318cd7596acbe8b03e5e1a3ee1448f619045d426bbeac33ec238e16649fb3abe09e6250d0238ebe5a5d5be5e557420ed048

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
